(source gnu)
(source melpa)

;; Generated
(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")

;; System-related
(depends-on "exec-path-from-shell")
(depends-on "with-editor")

;; Auto-compleate, search
(depends-on "auto-complete")
(depends-on "ac-helm")
(depends-on "helm")
(depends-on "helm-core")
(depends-on "helm-projectile")
(depends-on "smartparens")

(depends-on "projectile")

(depends-on "solarized-theme")

;; Language modes
(depends-on "coffee-mode")
(depends-on "fish-mode")
(depends-on "ghc")
(depends-on "ghci-completion")
(depends-on "gnuplot")
(depends-on "haml-mode")
(depends-on "handlebars-mode")
(depends-on "haskell-mode")
(depends-on "less-css-mode")
(depends-on "lua-mode")
(depends-on "ruby-mode")
(depends-on "ruby-block")
(depends-on "ruby-tools")
(depends-on "scss-mode")
(depends-on "slim-mode")

;; Checkers-linters
(depends-on "flymake-cursor")
(depends-on "flymake-easy")
(depends-on "flymake-haml")
(depends-on "flymake-haskell-multi")
(depends-on "flymake-less")
(depends-on "flymake-lua")
(depends-on "flymake-ruby")
(depends-on "flymake-sass")

;; VCS
(depends-on "git-commit")
